### ISSUE TITLE
Color Stripper

### ISSUE THREAD

**Issue by JamsRepos** [c0rp3n/colorlib-sm#3]
![Image](https://raffsimms.com/files/brave-0353.png)
Seems to remove the first letter of every players name.
![Image](https://raffsimms.com/files/explorer-0354.png)
As well as changed all messages to red.
![Image](https://raffsimms.com/files/explorer-0355.png)
Then changed them all to yellow.

**Comment by JamsRepos** [comment]
As well as, anything within { } brackets is rendered invisible too, if it's not a color.

**Comment by JamsRepos** [comment]
Seems if you put a bracket in front of your name, it can change the whole chat to a color so I think there might be a couple issues with colorlib or might be TTT?

**Comment by c0rp3n** [comment]
Hmm is it compiled with the latest version? believe I fixed this with https://github.com/c0rp3n/colorlib-sm/commit/cce3c3b9d75fccbf17bfe9d7f37ceafd3efdc1e3 please check else there could be a further issue that I havent noticed when testing the plugin.

Also for the messages being forced to a single color that is odd.
